In [13]:
import numpy as np
y = np.arange(42).reshape(6,7) # 6 rows and 7 columns 2D dimension array

print (y)

# passing a single index meaning row index
print (y[0]) 


print ('------------- returning column values into one dmentsional array -------------')
print (y[:, 0]) # row, column
# passing empty row, and 4th column index to return column values
print (y[:, 3]) # row, column


print ('------------- returning single cell value  -------------')
print (y[2, 3]) # row, column


print ('------------- Get first three elements of 4th column  -------------')
print (y[0:3, 3]) # row, column
print (y[:3, 3]) # row, column



print ('------------- Get a portion of the elements from selctive columns and rows from the matrix  -------------')
print (y[1:4, 0:2])
print (y[1:4, :2])
print (y[2:5, 2:5])



[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[0 1 2 3 4 5 6]
------------- returning column values into one dmentsional array -------------
[ 0  7 14 21 28 35]
[ 3 10 17 24 31 38]
------------- returning single cell value  -------------
17
------------- Get first three elements of 4th column  -------------
[ 3 10 17]
[ 3 10 17]
------------- Get a portion of the elements from selctive columns and rows from the matrix  -------------
[[ 7  8]
 [14 15]
 [21 22]]
[[ 7  8]
 [14 15]
 [21 22]]
[[16 17 18]
 [23 24 25]
 [30 31 32]]


In [15]:
print ('------------- Get every second row from the starting from the first row from the matrix  -------------')
print (y[0::2])
print (y[::2])


print ('------------- Get every other column starting from the first column from the matrix  -------------')
print (y[:, ::2])
print (y[:, 0:7:2])



print (y[1:6:2, 1:6:2]) # row, Column and Interval


------------- Get every second row from the starting from the first row from the matrix  -------------
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
------------- Get every other column starting from the first column from the matrix  -------------
[[ 0  2  4  6]
 [ 7  9 11 13]
 [14 16 18 20]
 [21 23 25 27]
 [28 30 32 34]
 [35 37 39 41]]
[[ 0  2  4  6]
 [ 7  9 11 13]
 [14 16 18 20]
 [21 23 25 27]
 [28 30 32 34]
 [35 37 39 41]]
