In [1]:
!pip install numpy

  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)


In [2]:
import numpy as np

x = np.array([2,5,1,9,0,3,8,11,-4,-3,-8,6,10])

## Basic Indexing

In [4]:
print(str(x[0]) + ', ' + str(x[3]) + ', ' + str(x[6]))

2, 9, 8


## Basic Slicing

#### Here <b style='color:blue; background:cornsilk;'>1</b> is the lower limit and <b style='color:blue; background:cornsilk;'>7</b> is the upper limit.  Output array starts from the element of <b style='color:blue; background:cornsilk;'>index 1 to 7</b>, lower limit included and upper limit excluded.  That means it includes the element in index 1 but does not include the element in index 7.

In [5]:
print(x[1:7])

[5 1 9 0 3 8]


## Slicing With Interval

#### In this case, 2 is the starting point and 3 is the interval.  So the returning array stars from the element in index two.  After that it takes every third element of the array till the end.  

In [11]:
print (x)

print (x[2::3])

# if we only want 3 elements
x[2::3][0:3]

# Interval Starting From The End or bottom of the list
print(x[-7::2])

# reverse interval
print(x[-7::-2])

[ 2  5  1  9  0  3  8 11 -4 -3 -8  6 10]
[ 1  3 -4  6]
[ 8 -4 -8 10]
[8 0 1 2]


## Default Beginning and Ending


In [7]:
# default begining or lower limit
print (x[:4])

# default ending or upper limit
print (x[4:])

# default beging and ending 
print (x[:])
  

[2 5 1 9]
[ 0  3  8 11 -4 -3 -8  6 10]
[ 2  5  1  9  0  3  8 11 -4 -3 -8  6 10]


## Slicing With Interval and Both Upper and Lower Limit

#### In x[1:7:2], 1 is the lower limit, 7 is upper limit and 2 in the interval.  Output starts in the element in index 1 and end in the index 7 but instead of outputting each element in between it outputs every second element as the interval is 2. 

In [8]:
print (x[1:7:2])

[5 9 3]
